spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/zafir"
    username: "root"
    password: "qwertydevix12"
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-message: always
